package xyz.verocs.teleporter;

import com.mojang.authlib.GameProfile;
import com.mojang.authlib.properties.Property;
import org.bukkit.Bukkit;
import org.bukkit.Material;
import org.bukkit.inventory.Inventory;
import org.bukkit.inventory.ItemStack;
import org.bukkit.inventory.meta.SkullMeta;
import xyz.verocs.utils.HeadBuilder;

import java.lang.reflect.Field;
import java.util.UUID;


public enum Heads {
	LUCKYQSG("MzNmMmNkOWY4MWEyNzcyYmRjNDg2NDQ3MmU4MzMzNjIzMTA0ODVjOGE2YmMwYjc2YjgxNzAzMzkwYTliMDMyZSJ9fX0="),
	BOBTHEBUILDER("MWVlNzY4OTUzZWQzZTY0NjRkZWY5NGMxMTllNTIzNjhiYTdlMTg0YWM2MjY2NzJjNjQ2Y2VkZGViNjNlZSJ9fX0="),
	RUNE_VEX("NDdhNGFmMGU0ZjQ5NDFlM2Y5ZDBiNTcwZDA5NzkwOTQ0MDY2YWM5NjMxMmFhZWFmMGNhODhhOTk5MmU1In19fQ=="), //58
	RUNE_LO("YmM2MDc1Y2FjN2QyZDVhYmM1NWIzMzkyNTY2ZDRhZGM1MjhkNDgxZjc3YmVjMGRlZjEzODVjOGJkYjIwNmM1NiJ9fX0="), 
	RUNE_LTH("YmFiODJjMTllYmI1MTdhMDg3Yzg5NGYzOTk2MjJlNzZhZjRhMTBiNDRlNjJjODdlN2RlYWUzZGM3YzgyMWUifX19"),
	RUNE_NEF("OTMyODY1NDA0ZjlhMzYxODQ5N2RmZTM1YmUyYzllOWViNDJlODc5ZDg0MDVlOGJmNWI2MjZkZmEyYTY5ZDQ2In19fQ=="),
	RUNE_LUM("Y2UxODlkOWZmYTViNjZjM2RkODE3NDkzYzhiMjg5NWVkM2U4MzM2MDZjOWViMWY1NTFiNWE5MzI1NmVmMTkifX19"),
	RUNE_TAL("YWRkYzk5Yjg2OTVjMjkwNmE0Mzc0YTg2OGFhMWU1OGYwZjcxMTdlMWE4YTlmZWEyNzNhOTFhODk1ZDY2YTQifX19"),
	RUNE_GUL("MmE0ZGZlNGYzYTU0MDQwM2RkNzQxODM5ZjU2YzY2OTNkMDQ4MTY1NWI5YTE0MjJkNTkyM2JkYjVmNjE5YiJ9fX0="),
	CHEST_MONEYBAG("Mzk2Y2UxM2ZmNjE1NWZkZjMyMzVkOGQyMjE3NGM1ZGU0YmY1NTEyZjFhZGVkYTFhZmEzZmMyODE4MGYzZjcifX19"),
	STRACE("MzJlYTg1Yzg1ZmUwNDg0YWY2YzgxNWVmYjY1NWQyYjIxZTEwOTg2M2M5NjMzM2I5MjgwYjU5YjgwZDZhYzk4ZiJ9fX0="), //1
	MINER1("YzRjODZjOThjYjhhZGE1MGFmZjc1ZWQzZjk2ZTJkOWU1OTAxOGNhOWI2MmJjOTU0OGY3ODE4Zjg0YWZjMDE3In19fQ=="),//2
	MINER2("YWIxMjRmY2UxNWM5NDk3YjljZTQ0MTUwMjZkZjFmYTJkODg2MTNhNWE4MWI0NGY4YjFmNzk0NWI4NmUwYTMifX19"),//3
	MINER3("NDY1YmIxOTJhNjU2YmQ2ZGVjOGQ4YzhlNGRiM2I1NzNjZjcxNjliYjczOTM5MTZlZjlhYzE5ZGExNjNhZGE1In19fQ=="),//4
	MINER4("YWU3N2FlNGYzNjUyZjY3MTIwM2NmNDVmZjNjN2Y3ZTYzMjhlOTIxYzM3NGE3YTMxMWIzZTQ4NDQ0ZmQ4OTIifX19"),//5
	MINER5("OTM3ZjhmOTVjMTI1NzU3Y2JmNzY3YTExZjUyYTRlNjY5MWNlMThhMjU5NzhjNjhjZmEzOTEwMzYwZmUifX19"),//6
	SLIME("YWM5MjU1NDI0OWVhMThjZjY3ODM4ZGRlMTdlNjY2MmY0NmMyMTk0ZjU3NWQyMDNmZjQzMmUzMzdhMDg4ZGYzYyJ9fX0="),//7
	CHEST_OPEN("YjZhY2ZjNjQzZjYwOGUxNmRlMTkzMzVkZGNhNzFhODI4ZGZiOGRhY2E1NzkzZWI1YmJjYjBjN2QxNTU5MjQ5In19fQ=="),//8
	Brombeere("MTNjNTM3OGQ0ZTBmMTQyMmJmMjZjYjU1YTBhZmRkOGViODljYjgyZDA2MjA1MDMzZmE1MmFiYmIwZDEwZDBlNiJ9fX0="),//9
	Erdbeere("NzQ3YWUwYjFlN2Q1NmI4ZDI4MmUyOWU0ODJlY2YwM2U0NjFlZWQ0OTFmOTFmMDE0ZWQzZWI5MDhmMjIyZTQ1In19fQ=="),//10
	Zitrone("NDM3OGI1ODJkMTljY2M1NWIwMjNlYjgyZWRhMjcxYmFjNDc0NGZhMjAwNmNmNWUxOTAyNDZlMmI0ZDVkIn19fQ=="),//11
	Blueberry("NDI2OTdmM2VmOGY0NjI5YjY0NWZkMmU2NDQ2NDEzMjRhMWMxMTgzNTQ5OGU2MzhmNzU3ZjI3OGFmYmNlNWRiMSJ9fX0="),//12
	Weintraube("NGUyNjQxOTIxMzhkNTM5ODhkOGU1NDAxMDM1OWI3YzUxMWQ4NmE0YmJkYWE1NThlZDFjNmIyYTRmNzM4MGJhIn19fQ=="),//13
	Dragonfruit("OTE1ZWM0ZjQyOTdlYTkzYmE5ZjdhN2IzOTdkZDQ3OGZiZDEyMTE4NWRlZGQ4NDZlZjhjNjdjNzQ4N2ZkMTEzMCJ9fX0="),//14
	Mais("ZDM5MWRmZmJlYTJmYzNmMmFkNzhhNjIzZjQ5YmY3ZTExMjE2OTQxMTJjMzc1OWZlZWQ0MTU2ZmMyYmE0NmMwIn19fQ=="),//15
	Rubin("ZjgzMjM2NjM5NjA3MDM2YzFiYTM5MWMyYjQ2YTljN2IwZWZkNzYwYzhiZmEyOTk2YTYwNTU1ODJiNGRhNSJ9fX0="),//16
	Amethyst("YTc5ZjhjOTI3NzZkNjQyZDExOWY5ZTkyMzYwYjFlNWI5NzFlNjZlNjE0MjhhM2UxYjMxMWQ4YjYxODVlNiJ9fX0="),//17
	Saphir("ZThjNTExYjk2MWIyZGNhMDEyZjNhNWY1YjQ2NjA3OGEwZWMyMzgwYTc2ZDUxOWVhMzY0YTdkNmRjMjhlMWJiIn19fQ=="),//18
	Aquamarin("YjkxYWVjYTdjMTdlNjZkODY3MjMxYjM2ZDk2ZTgzYzFlZGU3NWVhZjY3Y2NmM2E4OGRjYTE1ZDQxMTRhZTE2NyJ9fX0="),//19
	Diopsid("ZTZlMGQ1ZmU4N2QyZDIxZTJiZGU2Mzc0NDI1YTM0MWE3NTczYjM3NWQ1YmI3ZDQ3ZjRiOGRhZTM1Mjk3ZWE0In19fQ=="),//20
	Topas("ZTc0MTJhZTc1YjgyMmNlOWM5YWQ0Y2JhZTg3NTA2MWI2YmYzZGUyMzMzYWIxMzdjODJkNjYxZGQ5YmVmIn19fQ=="),//21
	CHEST_NORMAL("ZDVjNmRjMmJiZjUxYzM2Y2ZjNzcxNDU4NWE2YTU2ODNlZjJiMTRkNDdkOGZmNzE0NjU0YTg5M2Y1ZGE2MjIifX19"),//22
	CHEST_IRON("ZjdhYWRmZjlkZGM1NDZmZGNlYzZlZDU5MTljYzM5ZGZhOGQwYzA3ZmY0YmM2MTNhMTlmMmU2ZDdmMjU5MyJ9fX0="),//23
	CHEST_GOLD("ZjM3Y2FlNWM1MWViMTU1OGVhODI4ZjU4ZTBkZmY4ZTZiN2IwYjFhMTgzZDczN2VlY2Y3MTQ2NjE3NjEifX19"),//24
	CHEST_DIAMOND("MjU4MDdjYzRjM2I2OTU4YWVhNjE1NmU4NDUxOGQ5MWE0OWM1ZjMyOTcxZTZlYjI2OWEyM2EyNWEyNzE0NSJ9fX0="),//25
	CHEST_EMERALD("ZjNkNWU0M2RlNWQ0MTc3YzRiYWYyZjQ0MTYxNTU0NDczYTNiMGJlNTQzMDk5OGI1ZmNkODI2YWY5NDNhZmUzIn19fQ=="),//26
	CHEST_WINTER("OTI4ZTY5MmQ4NmUyMjQ0OTc5MTVhMzk1ODNkYmUzOGVkZmZkMzljYmJhNDU3Y2M5NWE3YWMzZWEyNWQ0NDUifX19"),//27
	CHEST_NEWYEAR("NWNiYjRmZGRhY2I1NDZkYmRmNjgyNzg0MGIxMmFiNDk5OTQzMmZjMmJhMjllOWJkZWU1MzNhNmRkMjU0ZmE4In19fQ=="),//28
	CHEST_OBSIDIAN("OWI0Y2E0MzU2ZTMzOGI4YjJjYWJmZWNkMmRjY2RmMzZjOWRlOWVmZTc3ZTg4NTE1NzExYWE0YWIxY2MifX19"),//29
	HEAD_JOKER("MmU0YTM1MmNiMzFhZjIxYjU3ZWI0YjQzMDI5YTRlMmNkNDU1ZjI1NThiYzBhMTA4OGNiNmZmOThlYjA3NjM5NiJ9fX0="),//30
	HEAD_WALUIGI("NTdjZDNkMWVlMDNiMmRkZDI1MDk4ZmZhNWY0YWIxMDU3YmM0M2U0ZWNkMTQ3ZWM0MWFhOGRmMzAyZTNlYjEwOSJ9fX0="),//31
	HEAD_GOBLIN("YTQ1ZWZmZDBiMGJkNmVhYzQ1M2YyOWZlNTJiZTRiYjVlOGJkNWJiZjRkOTVlYTE3YTYxYmIzZTRiZjZkNzNlNCJ9fX0="),//32
	HEAD_PRIESTERIN("ZDI1NTU3YmQ1YTgyYjBjMjEwNDVlMzIyMGMzMzgwYWM5ZTBlZDQ2ZGM4M2I1ZjAwYTlkZjJlM2QzZTUwNDVhMiJ9fX0="),//33
	HEAD_GOBLINSLAYER("ZDNmZDdkZGNjOThjMjU5MDU1ZThmMGFlMzcwMjg4NTdlOGVkMzQzMjUzYTc5OWE3Njg5NGQxOGNmNTJhYTRkMiJ9fX0="),//34
	HEAD_HOBGOBLIN("MzM4OTgzNGFjYzI1NmM2NTU2OTBjZjJhNjViMDZjZDc2NDMyNjk1NTJhOTg1NWYzZGExYTJjMGVkOWQ0NWY2ZSJ9fX0="),//35
	HEAD_ALBEDO("OTNmYmQyYjU1ZDJmM2YyNTdlYWE5NjI3OTM0ZDdlZjUxZGVlNmEyYTY0ZTc2Y2Y1MDY0NjRlMjIyMjFkYzllMCJ9fX0="),//36
	HEAD_STITCH("MmY3NjAwOWJlY2JkMGJlMTdmMzFiNzNkM2QxYWU0NWI5OTExNjk5MjYzYjc3OWE1ZTdkZjM2ZDkyYzBhYTNlZCJ9fX0="), //37
	HEAD_ZELDA("YTE0NWVhYzI4ZjE4MmEzNDliZWRhNWEyZDczZjA3YzVkZWE3YzY4ZmM2MWFlNGUyZjE3YWNlZThkNGZlYjUifX19"), //38
	HEAD_LINK("NmJiMmU2OWIzODcwZmUyZjRmMWJhMTRhOGY5Y2E4YWNjOWE3NTIwZTRlNGE5Nzg0YzE5YTNhMGM5NDQ2ZTRkIn19fQ=="), //39
	HEAD_SKULLKID("ZDFiZWM5ZWUzZjIwOTBjNzU2ZjhlNmYxZTQzZmUzZDA1NmVhY2IxZGRhNDAzMTExYzA4NGJhMjkzZWM1MjEifX19"), //40
	HEAD_GARON("ZGMxYWVlYTBjZDNiZWI2NTc4YzY4YzZhMWFlYWJiMmQyYWM3NmEzZjRlZTkzZmY2MjQzOTRmZDViZDJkZGMzIn19fQ=="), //41
	HEAD_ZORA("ZTViYzM3NWVhOTVhMmQ5ZTc0N2M1M2UzNDU3ZjY4Zjg5MDkzYzRlYjE1ZTA1NGE5Y2VmMWFjMmJmNWNjZSJ9fX0="), //42
	HEAD_SKELETONKNIGHT("YTJlZjBiMDdmNzFkZjUxNzQ1OWQ4MDQzZjcwMTM2ZGI3OWQyZDljNWE5NTlhM2I0NTI2ZDcxYmUxOGNiZWRhMCJ9fX0="), //43
	HEAD_RAINBOWPEEP("ZjUyYTFjNWEyYzIxNDIxY2U3ZjNlNzFhMDQ4N2RmNGZmOTRhZmI1Zjg5Y2U2ZDQ0ZWVhMDdjN2RlNGM1NDFiZCJ9fX0="), //44
	HEAD_MCDONALDSEMPLOYEE("OTliZWFhMDQxOGJmOWU5ZjA3OWY5OTUxZTJkZDk5NjI2ZTAzYTQ3MjZiMmNkNTA1YmRmYzk1NDcwYjNkYjVjNyJ9fX0="), //45
	HEAD_EMOTE_ERSCHROKEN("ZjcyMGRmOTExYzA1MjM3NzA2NTQwOGRiNzhhMjVjNjc4Zjc5MWViOTQ0YzA2MzkzNWFlODZkYmU1MWM3MWIifX19"), //46
	HEAD_EMOTE_CRYING("MWYxYjg3NWRlNDljNTg3ZTNiNDAyM2NlMjRkNDcyZmYyNzU4M2ExZjA1NGYzN2U3M2ExMTU0YjViNTQ5OCJ9fX0="), //47
	HEAD_EMOTE_CRYINGLOUDLY("MzI1NTg0NjQ2N2YzMzkzN2RiOWY0M2NkZmIzNGEwZGZkMTJmNTc1MjJlOGE5ODhlNDU4YjVhYzNjMTM0ZSJ9fX0="), //48
	HEAD_EMOTE_INLOVE("MTI5ZmI5ZjU5M2I2YWU1MzNkZmE4Y2U3OTYxNWZjYzM1ODk0YTQyY2JiNDFkZTU5OGQ2OTQ3NjczNTJmZSJ9fX0="), //49
	HEAD_EMOTE_ZUNGE("YzViN2YwYTE5OGJhYzc2N2RkNGYzMjUwMWJkMjllN2IyZmEzZTY1OWJmNGY2NjAxZGIwYjZhYjM0MzQ1Nzk4In19fQ=="), //50
	LETTER_G("YmZiZWY1ZTAyOGM4N2IwOTVlYTM4MDY0YzVmNTRlMmRkYjhlMGJhY2U2OWI0NmIyZjI5ZWVmODAxODgzNDhlNiJ9fX0="), //51
	
	HEAD_DURRBURGER("NjkzYjU3YmE0YWM2ZjA0MzE1ZmM0ODFkZTdhMjFlZjI3ZWNiNDhiYWIyNDM1OGEyZWM3MjIwMjBkYzVmYzg1ZSJ9fX0="), //52
	CHEST_DIRT("ZmMyN2IzODdjMzNlMDhmOWQyNmRkNWM4Y2U0ZWJhNzFkOTZlMDhkOTVlNzFlZGRkYzE0MDY0NzJhMDM0In19fQ=="), //53
	HEAD_Librarian_Villager("NzFmNzE0MTMzY2U3OGQxMTgxYzRkNWQzZTUzNzExZWNlMTBjNGM5YTI4MjAxMTg4ZWUxYTZmMzVjYzBmYTNjYSJ9fX0="), //54
	HEAD_Leatherworker_Villager("NTAwN2M0YTNlM2I4ZDMxYjk0YTk1MTczYmMyYWVhNGI3MThjMTUwZjAxNjZmMGM5NjRjYTllMDRiZTY2NGEyMiJ9fX0="), //55
	HEAD_Cartographer_Villager("ZjJmOTQ0MjIyZmY2OTNmZTA4OGJkNTQzYzhlZmRkMzI0NmVhYjZhMzQ5NzhhY2RlNzc0ZjdlMjk1ZGVlOWUxNiJ9fX0="), //56
	HEAD_Armorer_Villager("ZWRjYjIxMDkwY2Q3ZTk3MDY2YTFmMWRjYWU3NzhjZGEwMzJkZjhhZjk1Mzc2N2QyYTA0ZjRhNzhkY2ZjMjQ5NiJ9fX0="), //57
	
	
	//BACKPACKS
	BACKPACK_NORMAL("ODM1MWU1MDU5ODk4MzhlMjcyODdlN2FmYmM3Zjk3ZTc5NmNhYjVmMzU5OGE3NjE2MGMxMzFjOTQwZDBjNSJ9fX0="), //1
	BACKPACK_RED("NWNkMjg3NzI3ZDMzOTY3NTkyNjM3Yjk1M2Q1NzM1NTg2ZWM0ZDAxYjFiNTE2MGMwYWRiMzQ5YzQ2NzVkYjQifX19"), //2
	BACKPACK_BROWN("MWU5MGY4ZTdlMzZmZTU1MmViMzVkMDM3MWUwNDRkMTJmYjQyZWE4YjFjNmI1OGE3NGJkMjRmNWVjN2Q4OWM0ZSJ9fX0="), //3
	BACKPACK_NAVY("OGRjYzZlYjQwZjNiYWRhNDFlNDMzOTg4OGQ2ZDIwNzQzNzU5OGJkYmQxNzVjMmU3MzExOTFkNWE5YTQyZDNjOCJ9fX0="), //4
	BACKPACK_REDSTRIPPED("ZWNlODMzYWE5YTI4YmNmMjA3ZTViMzZhNTkxY2VmMWY5OTdkZDJmNGE0YTIzNmFmNTBkZDA4MWYzYTVkOWM0YyJ9fX0="), //6
	BACKPACK_ENDER("YjEyYzBhMzljZjQ2YTcyYzE4ZmJhMzA3YjgxNTQ2MmQxOTk3NGZlZWU3YTA3ODY0MzU2OWRlY2JmNWI3In19fQ=="), //8
	BACKPACK_CAMO("ZjhjMTVhYTc5MmVjOTFmYzJkYWY1N2RiZjI3ZjM3YTg4NjUzODU0MWExODBhZjg4YjE0MTVlZTM3ZDEyYTcifX19"), //9
	BACKPACK_YELLOW("YTI1NGFhY2JmNjIzMTc1ZmY5OGRmN2FlMzY2ZTBiODllOTE3MTM0NDE3NTJmM2NkZjk2NWYwMzhiMTc0YjUifX19"), //10
	BACKPACK_WHITE("ZWJkZjhkNTNiZGI5MzJjMjIzYzYyN2JiYjhjMWUwYzVlMzUxYTYxNmNkODA1NjkyOWM2NmU2ZGNlNDQ0MzNkYiJ9fX0="), //11
	BACKPACK_DARKRED("ODVlNGY5ZGE2OGM4MWZhNDgxZWVjZGNhNDhhMTM4Y2VjZGUyY2RkZmZlZWFlODRhYjFhZmQyNGEzNjNlMDI4In19fQ=="), //12
	BACKPACK_PURPLE("NWViNjViYmU3NDQ5NDU4NDFlOTIzNGEzM2I1Y2U1Y2MyMzZmNmEyZmM5M2ExYTNhZTQyZGY3N2M5MDg0ZGYxZSJ9fX0="), //13
	BACKPACK_PINK("YmRkYWZkY2IxYThkZjQyNjIyOWQ3ODc5YjFlNGEzMzZmYzlhYjNiZGMxNDZiYjRlZDNiZTRiYmY3YjViODM1In19fQ=="), //14
	BACKPACK_ORANGE("YTM3YTM1NTIyZjY3YjJhZjkyMzQ1NTkyODQ2YjcwMmI5YWZiOWQ3YzhkYmFkNWVhMTUwNjczYzllNDRkZTMifX19"), //15
	BACKPACK_MAGENTA("MzY1NzVmY2NjYWRhZTg3YzA4NDJmNTNkZTVlMGZmYTc1ODUxNjk2ODY2ZDgxZTFiNzI4MjgzNDhkYjUyNTYifX19"), //16
	BACKPACK_CACTUSGREEN("YTk5MDlhOTc3OWI5NDZiOTc4NzQ0MmZhNDgzYWY0ZGU0YjJmMTlmZDQwZGMyMzcwZjdhOWI4ZjUyMWYyMWRkYyJ9fX0="), //17
	BACKPACK_LIGHTGRAY("NWE1ZmM3NjM1Mjk2Y2ExODNmZDMwYjBmYjVmNGMxOGNmYzIxNjc2OGYwZmJlYmI4NjVlMDIxMWFiNDNiN2IifX19"), //18
	BACKPACK_BLUE("YTNjMTUzYzM5MWMzNGUyZDMyOGE2MDgzOWU2ODNhOWY4MmFkMzA0ODI5OWQ4YmM2YTM5ZTZmOTE1Y2M1YSJ9fX0="), //19
	BACKPACK_GRAY("NjUzNmFkOTc4ZTFjZTUwNTBmNDNiN2E2YjM4NTllYjQ5NDA2YjRmMTA0MzgwMmE3MTFjZGM4MGMwOTBjMzVkIn19fQ=="), //20
	BACKPACK_GREEN("MjhhMTI3ZjFjZmQ3OTk4NmU3YmQ5NWQ5MmRlNGY0ZjY4MDQwZTRmODk5ZjgxYjFmOGYzY2ExNWI2NGY1MGYzIn19fQ=="), //21
	BACKPACK_CYAN("ZGY3MGZhYjMyNDZmZTAyN2NlMGJiYTg4NWE3M2M2ZTgyZDhmZjhmMzU4MjMxZTg0NjFmOTU2NTYwY2ZhNThmIn19fQ=="), //22
	BACKPACK_DARKBROWN("ZWZiNmEzZDdkYmE5N2JiNmU3Zjc5YTE1NjI3YWVjNjM2OTc5MTIzM2Y4MzNmYTc0OWVmMjFiZWQ3OWU1OWU5OCJ9fX0="), //23
	BACKPACK_DARKBLUE("vODIyNGIyYzczOTFlYjViZmNiMjc4NDMxZDVjODI3Y2IyNjM0OTUyNmM3YmM1MzViMWU5NWY2ZGY5ZjNmZGYzIn19fQ=="), //24
	BACKPACK_BLACK("YTlhYjFmZGNiZTg3OGQxZTU1YmRkNDNjZWJjNWU0MzgzNmE2ZGE2OTU0MWY0YTIzM2ZlODhmMTMwNTY2OCJ9fX0="), //25
	BACKPACK_LIGHTBROWN("NTg0NTlmM2I2NWIyM2NmYThjOWIxNDQzMjViOWJhODE0MDdiZTkzODJjZDg1OTkyZWY5NzljZjBlNzgzZjYifX19"), //26
	
	BACKPACK_EASTERN_BASKET("ODNjMjVhN2ExODgxOTZiMTg3MTcyNjRmZmU4MzdjYTM0OGNmNzE5ZTgyNzE3OWVkYzRiNzhjYmNiOGM3ZGQ4In19fQ=="), //27
	BACKPACK_TRICKORTREAT_BASKET("ZjZjNjViZjI3YjgzZmMyZDJkMTdjMDY2OTg5OTE4M2NkZWRiNTU1NjQyYWVlYjgyYjU3ZWRkNmVkMWFkYTRmMCJ9fX0="), //28
	BACKPACK_COOLER_BASKET("MzY0ZmJlMjEzMWRhNzJlYTRiZjU1ZDQ5NTYwZmQ4OGQ2OGY5NTBhYjcwZWUxNmJlMGIwYmY3MmIyNGI5OGE2NiJ9fX0="), //29
	BACKPACK_SANTAS_BAG("YWIzMzliMWNkNDAwNTNkZWZkN2QzNTI4ZTAxZmVhODc2ZDQxYjQyZjlkOTI2ODQ2MWRhNzlmNWY2Njc3MTIzNiJ9fX0="), //30
	BACKPACK_FESTLICH("YjE0MWNhNTNmNjk1ZDlhMDM4NWFiMGViMWQ3MTE5ZjMzYzgwOTczNjUwMjU0MGMxZDhhMTcyNmNmMjFkNGYifX19"), //7
	
	BACKPACK_GUCCI("Y2UyYTE0YmE5NjBkNTA2MjgwOWExNGM5NzcyMjkzYzg3YTczMmRkMjZiZDk0YWFlNmVhMGU3MWVmZTk3ZWNkZiJ9fX0="), //5
	
	LOOTBAG1("NzE3YWI1OTkxYWFkNjJhMmE5ZWIzY2NmOTE0YzM1ZTI2ZmMzYmM2MGQ5MjU3NTUyMDIwYmUxM2YyZjZlYTUxMiJ9fX0="),
	LOOTBAG2("YjNlMDQzNmEwYmM2MDNlMDliMTlmZDA3YjI5OGM4ZmY4ZDM0OWE2MGYxYmE2Nzk2OTI4ZDUyYWYyZTk4NWVmMCJ9fX0="),
	LOOTBAG3("MzkyNzRhMmFjNTQxZTQwNGMwYWE4ODg3OWIwYzhiMTBmNTAyYmMyZDdlOWE2MWIzYjRiZjMzNjBiYzE1OTdhMiJ9fX0="),
	LOOTBAG4("NmU3YWFmMGJmZGNlMmZkMDM0NTQwYTM2MjIwNTc0NmFlMTMzM2Q4ODZkYTk4ZTdhY2JkY2IxNzA0N2Y5ZDA0NCJ9fX0="),
	LOOTBAG5("NjE3NmE0YzQ0NmI1NGQ1MGFlM2U1YmE4ZmU2ZjQxMzE3Njg5ZmY1YTc1MjMwMjgwOTdmNjExOTUzZDFkMTI5NyJ9fX0="),
	LOOTBAG6("MjA4MDAzYWUxZGVjNjQxN2IxNDA3MDQ2MjdhMDA3MTk2ZTUxNmFlZWM5YjM5NGFmNzhkNzAxOTJjOGUzNTE1ZCJ9fX0="),
	LOOTBAG7("ZjM0MzQ4ZDMzOWE3YmRiYjRkYzNlYTM5YzM0NDQ3Y2E3NjM4NDZiMjllMDZmNTY4ZTBjOGM1MjE5MjAzZGY5ZiJ9fX0="),
	LOOTBAG8("NzJlNjA4MWM4MjVlODM5NzdhNjE0ODI4YjE5ZmFiNThjMWY2ZTYzMzcwY2IxMDk1ZGE1MzU5ODQwZDhjZTExNiJ9fX0="),
	LOOTBAG9("NzYwYTA4ZGE4ZDNlNzNjNWFkZGNjMTAzODk1NjU2YWM0MDRmZjQyZjJkNWI1Yjc0NmNjZGU2MDdjZTkwNDQzYyJ9fX0="),
	LOOTBAG10("MWU1NTc0YTRlZjk0ZWY0Y2EzMDBkMDJmNjQ0ZDk4YmUwN2RiZmJhN2RmNzg4MDhlOGE5YTAyMWIwNjdkOTk2ZCJ9fX0="),

	
	;
	public String getPrefix() {
		return prefix;
	}


	public void setPrefix(String prefix) {
		this.prefix = prefix;
	}


	public String getTexture() {
		return texture;
	}


	public void setTexture(String texture) {
		this.texture = texture;
	}


	String prefix = "eyJ0ZXh0dXJlcyI6eyJTS0lOIjp7InVybCI6Imh0dHA6Ly90ZXh0dXJlcy5taW5lY3JhZnQubmV0L3RleHR1cmUv";
	String texture;

	Heads(String texture) {
		this.texture = texture;
	}
	
	
	public static HeadBuilder createHead(Heads head) {
		
		String url = head.getPrefix() + head.getTexture();
		ItemStack skull = new ItemStack(Material.SKULL_ITEM, 1,(short) 3);
		SkullMeta meta = (SkullMeta) skull.getItemMeta();
		GameProfile profile = new GameProfile(UUID.randomUUID(), null);
		
		profile.getProperties().put("textures", new Property("textures", url));
		try {		
			Field profileField = meta.getClass().getDeclaredField("profile");
			profileField.setAccessible(true);
			profileField.set(meta, profile);
			
			
		} catch (IllegalArgumentException|NoSuchFieldException|SecurityException|IllegalAccessException  error) {
			error.printStackTrace();
		}
		skull.setItemMeta(meta);
		
		
		return new HeadBuilder(skull);
		
	}

	public static Inventory preLoad() {
		Inventory inv = Bukkit.createInventory(null, 6*9);
		for(Heads head: Heads.values()) {
			if(!head.name().contains("BACKPACK"))
			inv.addItem(createHead(head).build());
		}
		return inv;
	}
	public static Inventory preLoadBackpacks() {
		Inventory inv = Bukkit.createInventory(null, 6*9);
		for(Heads head: Heads.values()) {
			if(head.name().contains("BACKPACK")) 
			inv.addItem(createHead(head).build());
			
		}
		return inv;
	}
}
